spring.application.name=agent-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/agent_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=pguser
spring.datasource.password=${db.password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.ai.google.genai.api-key=${apiKey}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
#gemini-3.1-flash-lite-preview
#gemini-2.5-flash, gemini-2.5-flash-lite
spring.ai.google.genai.chat.options.temperature=0.7

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

agent.max-iterations=10
agent.max-cost-tokens=5000

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest