spring.application.name=agent-service

server.port=8082

#spring.ai.google.genai.vertex-ai=false
#spring.ai.google.genai.project-id=none
#spring.ai.google.genai.location=none
spring.ai.google.genai.api-key=${apiKey}
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite-preview
#gemini-3.1-flash-lite-preview
#gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
